[package]
name = "rlsh"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
rand = "0.9.1"
rmp-serde = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
whoami = "1.6.0"
tokio = { version = "1", features = ["full"] }
